# Generated by Django 3.1 on 2020-08-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=1000)),
                ('mobile', models.IntegerField(max_length=20)),
                ('ammount', models.IntegerField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='destination',
            name='email',
            field=models.EmailField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='destination',
            name='mobile',
            field=models.IntegerField(max_length=20),
        ),
    ]
