# Generated by Django 3.1 on 2020-08-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200830_1341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bank',
        ),
        migrations.AlterField(
            model_name='destination',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
    ]
