# Generated by Django 3.2.4 on 2022-04-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200830_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='fuel',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
