# Generated by Django 3.2.4 on 2022-04-17 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_destination_fuel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='destination',
            unique_together={('email', 'mobile')},
        ),
    ]
