# Generated by Django 3.2.4 on 2022-04-17 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_destination_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='destination',
            unique_together=set(),
        ),
    ]
