# Generated by Django 3.2.4 on 2022-04-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_destination_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='fuel',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
