# Generated by Django 3.2.4 on 2022-04-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='contact',
            name='firstname',
            field=models.CharField(default='DEFAULT VALUE', max_length=300),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lastname',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='destination',
            name='email',
            field=models.EmailField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='fuel',
            field=models.CharField(default='DEFAULT VALUE', max_length=300),
        ),
        migrations.AlterField(
            model_name='destination',
            name='mobile',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
