# Generated by Django 3.2.4 on 2022-04-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20220422_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
    ]
